services:
  postgres:
    image: postgres:14
    container_name: postgres-local
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
